{{- if .Values.toolsets | not | empty }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: holmes
  name: custom-toolsets-configmap
  namespace: {{ .Release.Namespace }}
data:
  custom_toolset.yaml: |-
    toolsets: {{ toYaml .Values.toolsets | nindent 6 }}
{{- end }}
